on:
  workflow_dispatch:
  push:
    tags: ['v*.*.*']
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate Tags (In Subdir)
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: laoyutang/hp-lite-client
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./hp-client
          file: ./hp-client/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
