on:
  workflow_dispatch:
  push:
    tags: ['v*.*.*']
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: 'hp-web/package-lock.json'

      - name: Build Frontend
        run: |
          cd hp-web
          npm ci --omit=dev
          npm run build

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate Tags (In Subdir)
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: laoyutang/hp-lite-server
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./hp-server-golang/hp-server-lib/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
